services:
#    boutique_produits.example:
#        class: Boutique\ProduitsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.client.stripe:
        class: Boutique\ProduitsBundle\ServiceHandler\StripeClient
        arguments: ['%stripe_secret_key%', '%payment%', '@doctrine.orm.entity_manager', '@logger']

    