services:
#    boutique_produits.example:
#        class: Boutique\ProduitsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.client.stripe:
        class: Boutique\ProduitsBundle\ServiceHandler\StripeClient
        arguments: ['%stripe_secret_key%', '%payment%', '@doctrine.orm.entity_manager', '@logger']
    boutique_produits.display.message:
        class: Boutique\ProduitsBundle\ServiceHandler\DisplayMessage
    boutique_produits.event_listener.redirection_subscriber:
        class: Boutique\ProduitsBundle\EventListener\RedirectionSubscriber
        arguments: ['@router', '%supported_languages%', '%locale%']
        tags:
          - { name: kernel.event_subscriber }
    boutique_produits.event_listener.connexion_subscriber:
        class: Boutique\ProduitsBundle\EventListener\ConnexionSubscriber
        arguments: ['@router','@service_container']
        tags:
          - { name: kernel.event_subscriber }


    